---
# tasks file for ansible-wireguard
- name: Upgrade everything
  apt:
    name: "*"
    update_cache: yes
    state: latest
  
- name: Debian - installing necessary packages
  apt:
    state: latest
    pkg:
    - dirmngr
    - git
  when: ansible_architecture == 'x86_64'

- name: Raspberry Pi - installing necessary packages
  apt: 
    state: latest
    pkg: 
    - raspberrypi-kernel-headers
    - dirmngr
  when: ansible_architecture == 'armv7l'

- name: Pi Zero - installing necessary packages
  apt: 
    state: latest
    pkg: 
    - raspberrypi-kernel-headers
    - libmnl-dev
    - libelf-dev
    - build-essential
    - git
  when: ansible_architecture == 'armv6l'

- name: Pi Zero - clone Wireguard source
  git:
    repo: https://git.zx2c4.com/WireGuard
    dest: ~/wireguard-source

- name: Pi Zero - Build Wireguard from source
  make:
    chdir: ~/wireguard-source
  when: ansible_architecture == 'armv6l'    

- name: Pi Zero - Install Wireguard from source
  make:
    chdir: ~/wireguard-source
    target: install
  become: yes
  when: ansible_architecture == 'armv6l'  

- name: Make sure debian unstable repository is present
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    state: present
    filename: unstable
  when: ansible_architecture == 'x86_64' or ansible_architecture == 'armv7l'

- name: Add an apt keys from keyserver.ubuntu.com
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
    state: present
  with_items:
    - 8B48AD6246925553
    - 7638D0442B90D010
    - 04EE7237B7D453EC
  when: ansible_architecture == 'x86_64' or ansible_architecture == 'armv7l'

- name: Make sure are necessary packages are up-to-date
  apt:
    state: latest
    update_cache: yes
    pkg:
    - wireguard
