---
# tasks file for ansible-wireguard
- name: Upgrade everything
  apt:
    name: "*"
    update_cache: yes
    state: latest

- name: Make sure are necessary packages are up-to-date
  apt:
    state: latest
    pkg:
    - raspberrypi-kernel-headers
    - dirmngr

- name: Make sure debian unstable repository is present
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    state: present
    filename: unstable

- name: Add an apt keys from keyserver.ubuntu.com
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: {{ item }}
    state: present
  with_items:
    - 8B48AD6246925553
    - 7638D0442B90D010
    - 04EE7237B7D453EC

- name: Make sure are necessary packages are up-to-date
  apt:
    state: latest
    update_cache: yes
    pkg:
    - wireguard